name: Build and Release

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      manual_bump:
        description: 'Manual Version Bump'
        type: choice
        options:
          - 'disable'
          - 'patch'
          - 'minor'
          - 'major'
        default: 'disable'

permissions:
  contents: write

jobs:
  version_check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version-string }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    
    - name: Run Semver
      id: semver
      uses: bitshifted/git-auto-semver@v2
      with:
        main_branch: main
        initial_version: '1.0.0'
        create_tag: true
        tag_prefix: "v"
        manual_bump: ${{ inputs.manual_bump != 'disable' && inputs.manual_bump || '' }}

  build:
    name: Build Windows
    needs: version_check
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE
      env:
        PYTHONIOENCODING: utf-8
      run: |
        python build.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: dist/*

  release:
    name: Create Release
    needs: [build, version_check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Needed for git log history

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-windows
        path: dist

    - name: Generate Release Name
      id: release_name
      run: |
        MSG=$(git log -1 --pretty=%s)
        VERSION="v${{ needs.version_check.outputs.version }}"
        echo "title=$VERSION - $MSG" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.version_check.outputs.version }}
        name: ${{ steps.release_name.outputs.title }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: dist/*
